### ISSUE TITLE
:Scope Grep does not take into account 'wildignore' content.

### ISSUE THREAD

**Issue by ubaldot** [girishji/scope.vim#34]
I have `set wildignore+=.*/,**/.*,**/**cache**,**/*.o` and `:Scope File` works well. However, `:Scope Grep` does not seem to work well. For example, with this settings, it returns a number or `.git/` hits.

**Comment by girishji** [comment]
Is it on windows? On windows it uses `findstr` by default even if you have installed grep. Maybe I can check if grep is installed and use it instead. Can you check what `:echo &grepprg` says?

**Comment by girishji** [comment]
On windows, Vim does not recognize `grep` even if installed. You can check `grepprg`. I'd like to keep the same behaviour for this plugin. You can write a function to filter out `wildignore`, check GrepCmd() in util.vim file.

**Comment by girishji** [comment]
`findstr` has no straightforward way to skip directories when searching with `\s` option. It seems the only option is to run complicated scripts (https://stackoverflow.com/questions/20076262/findstr-and-skipping-folders). I do not consider piping through a filter (to exclude) directories is a good idea, since it still searches all the unwanted subtrees. So, closing this issue for now.
